import type { Profile } from "./types";

export const TIMEZONES = [
  "America/Los_Angeles",
  "America/Denver",
  "America/Chicago",
  "America/New_York",
  "America/Vancouver",
  "America/Toronto",
  "America/Mexico_City",
  "America/Sao_Paulo",
  "Europe/London",
  "Europe/Dublin",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Madrid",
  "Europe/Rome",
  "Europe/Amsterdam",
  "Europe/Stockholm",
  "Europe/Warsaw",
  "Europe/Moscow",
  "Asia/Shanghai",
  "Asia/Hong_Kong",
  "Asia/Taipei",
  "Asia/Tokyo",
  "Asia/Seoul",
  "Asia/Singapore",
  "Asia/Kolkata",
  "Australia/Sydney",
  "Pacific/Auckland",
];

export const LANGUAGES = [
  "en-US",
  "en-GB",
  "en-CA",
  "en-AU",
  "en-NZ",
  "en-IE",
  "zh-CN",
  "zh-TW",
  "zh-HK",
  "ja-JP",
  "ko-KR",
  "de-DE",
  "fr-FR",
  "es-ES",
  "es-MX",
  "pt-BR",
  "it-IT",
  "nl-NL",
  "sv-SE",
  "nb-NO",
  "da-DK",
  "fi-FI",
  "pl-PL",
  "tr-TR",
  "ru-RU",
];

export function newBlankProfile(): Profile {
  return {
    id: "",
    name: "",
    proxy: {
      protocol: "socks5",
      host: "127.0.0.1",
      port: 1080,
      username: null,
      password: null,
    },
    timezone: null,
    language: null,
    telemetry: { disableSentry: false, disableStatsig: false, disableSparkle: false },
    injection: {
      injectTimezone: false,
      injectLanguage: false,
      leakProtection: true,
      syncCodexEnv: true,
    },
    appPath: null,
    createdAt: 0,
    updatedAt: 0,
  };
}
